theme: jekyll-theme-minimal
title: Distant Reading in Literary Studies. An Introduction to Tools for Data Literacy, Bielefeld, Dec 7th 2022
logo: images/uni-bib2.jpeg
description: Official Workshop Webpage
